import Footer from "@/components/footer/Footer";
import Topbar from "@/components/header/Topbar";
import Categories from "@/components/home-page/Categories";
import Client from "@/components/home-page/Client";
import DealBanner from "@/components/home-page/Cta";
import FaqAccordion from "@/components/home-page/Faq";
import Features from "@/components/home-page/Features";
import GoogleReviews from "@/components/home-page/GoogleReviews";
import HeroSection from "@/components/home-page/HeroSection";
import ProductSlider from "@/components/home-page/ProductSlider";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>One Prime Studios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main-page">
        <div className="container">
          <Topbar />
          <HeroSection/>
          <Features/>
          </div>
          <Categories/>
          <GoogleReviews/>
          <ProductSlider/>
          <Client/>
          <ProductSlider/>
          <div className="container">
            <DealBanner/>
            <FaqAccordion/>
          </div>
       

          <Footer />
        
      </div>
    </>
  );
}
